name: Generate POT

on:
  push:
    branches:
      - master
      - main

jobs:
  WP_POT_Generator:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - name: WordPress POT Generator
        uses: afragen/action-wp-pot-generator@main
        with:
          save_path: "./languages"
          item_slug: "${{ github.event.repository.name }}"
          domain: "${{ github.event.repository.name }}"
          package_name: "${{ github.event.repository.name }}"
          headers: '{"Report-Msgid-Bugs-To":"https://github.com/${{ github.event.repository.full_name }}/${{ github.event.repository.name }}/issues"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
